events {}

http {

    server {
        listen 80;
        server_name multi-featureban.online;

        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name multi-featureban.online;

        ssl_certificate /etc/letsencrypt/live/multi-featureban.online/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/multi-featureban.online/privkey.pem;

        location / {
            proxy_pass http://frontend;
        }

        location /api/ {
            proxy_pass http://backend:8080;
        }

        location /ws/ {
            proxy_pass http://backend:8080;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
}
